name: validate sot
on:
  pull_request:
    types: [opened, synchronize, reopened]
run-name: run-validation

jobs:
  run-validation:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Checkout csv-validator tool
        uses: actions/checkout@v4
        with:
          repository: GDC-ConsumerEdge/csv-validator
          path: csv-validator
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: run validator
        run: |
          pushd csv-validator
          python3 -m pip install -r requirements.txt
          python3 -m pip install .
          popd

          validate_csv -v -m module/validation/cluster_intent.py wei-source-of-truth.csv
